# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0041de30cf91a013f4f6facb9feaee23587e380ac9e505cd7994c052cb24c6b8ddac29605855637187e4c43fdcfb35a4e69929419bf784802386df208aa73e

test:
  secret_key_base: 74626c1f66321e6c8b228e8c7afa70486326d92534220154340bb5cba2e1ee20f3cb715837938939e55d17612a6960a755ad7f65d5d6294a6f92deae47f38d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
